### ISSUE TITLE
Create API Views for Posts (Item) 

### ISSUE THREAD

**Issue by iesteban** [Semillas/semillas_backend#2]
Endpoint for the feed of items (posts) the user will see: 

-/api/v1/posts/feed -> The feed ordered by the location/publishing time of the user.
    - URL parameters: 
    - Lat: Latitude to order by geolocation
    - Lon: Longitude to order by geolocation
    - category: Category id to filter by that category
    - search: String to search item using that string

The default order should be by distance. 

In the future, another get param can be order with two options: distance, recent

**Comment by pilamb** [comment]
The order should be...
To Be continued!

**Comment by s-nt-s** [comment]
duplicates #20
